services:
  redis:
    image: "redis:latest"
    container_name: "redis"
    volumes:
      - redis_data:/data
    restart: always
    command: redis-server --appendonly yes --requirepass pluto
    ports:
      - 6479:6379
    networks:
      - pluto-network

  mongo:
    image: "mongo:latest"
    container_name: "mongo"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_DATABASE=auth
      - MONGO_INITDB_ROOT_PASSWORD=pluto
    restart: always
    ports:
      - 28017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - pluto-network

  pluto:
    build:
      context: .
      dockerfile: './Dockerfile'
    container_name: "pluto"
    depends_on:
      - redis
      - mongo
    command: tail -f /dev/null
    restart: always
    networks:
      - pluto-network

volumes:
  redis_data: {}
  mongo_data: {}

networks:
  pluto-network:
    driver: bridge