# Workflow's name
name: linux-clang

# Run this workflow every time a new commit pushed to your repository
on: [push, pull_request]

jobs:
  linux-clang:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        run: |
          sh build.sh