
# Workflow's name
name: macos

# Run this workflow every time a new commit pushed to your repository
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        run: |
          sh build.sh
      - name: Output
        run: |
          ls build/pluto
