# Workflow's name
name: ubuntu

# Run this workflow every time a new commit pushed to your repository
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Dependencies
        run: |
          sudo apt install -y libreadline-dev
      - name: Build
        run: |
          sh build.sh
      - name: Output
        run: |
          cd build/pluto && ls luaclib && ls cservice && ls