# Workflow's name
name: ubuntu

# Run this workflow every time a new commit pushed to your repository
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        run: |
          sh build.sh
      - name: Output
        run: |
          find build/pluto -type f
      - name: Run
        run: |
          cd build/pluto && ./skynet examples/config